### ISSUE TITLE
Responsive chart

### ISSUE THREAD

**Issue by Surenapetrosyan** [d2bjs/vue-d2b#1]
Hi, sorry to write this as an issue I just don't know how else to contact you. 

I can't figure out how to make the chart responsive to the width of the parent element. I am creating an axis chart and the chart is always whatever set width I set it to, but responsive widths like 100% don't work.

I know its possible because the axis chart demo on http://www.d2bjs.org/ does exactly what I'm looking for, but I can't seem to find the implementation in the documents. 

Please help, thank you.

**Comment by kevinwarne** [comment]
Hi there. I'm happy to help you get this working. By default all vue-d2b charts listen to the window resize event and then whenever this triggers they will re-render according to their parent dimensions. Here is a JS Fiddle to see this in action [https://jsfiddle.net/t6Lo275w/](https://jsfiddle.net/t6Lo275w/). Of course if you are using node and es6, your library and module imports will probably look different. Here you can see that the styles of the outer '.chart' container influence how the chart will be bound. If you need more control than this you can use the `updateDefer` method on the chart component to programmatically trigger the resize.

**Comment by Surenapetrosyan** [comment]
Hey Kevin,

Thanks so much for the reply, I got it to work. Awesome library by the way!

**Comment by kevinwarne** [comment]
Glad to hear you got it working! Let me know if you have any other questions or find bugs.
