### ISSUE TITLE
How do I pass additional data to the tooltip in a sankey diagram?

### ISSUE THREAD

**Issue by aamirkhancr7** [d2bjs/vue-d2b#10]
I am trying to display some extra info per node and per link through the tooltip. I am unable to figure out how to do this. Here is what I've tried:

```
chartConfig(chart) {
                chart.tooltip().html(function(d) {
                    console.log('hello');
                    return (d.key);
                });

                chart
                    .sankey()
                    .sankey()
                    .nodePadding(100)

                chart
                    .sankey()
                    .nodeDraggableY(true)
  }

```

But it says that chart.tooltip() is not a function. How do you pass some custom data to the tooltip here?. Any help with this would be great.

**Comment by kevinwarne** [comment]
Hey there,

You are very close but instead of using `chart.tooltip()` for the sankey you must use `chart.nodeTooltip()` or `chart.linkTooltip()`.

So something like..

```javascript
    chartConfig(chart) {
      chart.nodeTooltip().html((d) => {
        console.log(d);
        return d.data.name;
      })
    }
```

Hope this helps!

**Comment by kevinwarne** [comment]
Side note.. as of the latest d2b version these configurations can be included into the chart data itself. So the above would be..

```javascript
        chartData: {
          node: {
            tooltip: {
              html(data) {
                return data.name
              }
            },
          },
          ...
        }
```

You can even embed the tooltip content directly into the node object itself..

```javascript

        chartData: {
          nodes: [
            {name: 'Node A', tooltip: 'Custom tooltip for node A..'},
            {name: 'Node B'},
            {name: 'Node C'},
            {name: 'Node D'},
            {name: 'Node E'},
          ],
          ...
        },
```

And the same carries for links as well.

You can find the documentation for these properties [here](http://docs.d2bjs.org/chartsAdvanced/sankey.html#properties). But there are a lot of them so it easy to get lost.

Cheers!

**Comment by aamirkhancr7** [comment]
Thanks! figured it out. Also one more thing is it possible to add formatting to the node name as well (such a going to a new line, colors. etc.)?
