### ISSUE TITLE
remove axis-chart's intermediate points

### ISSUE THREAD

**Issue by maximus1010101** [d2bjs/vue-d2b#3]
In the example chart there are intermediate points.
Site page: [http://docs.d2bjs.org/vue-d2b/#/]
Your points:
```
{x: 1, y: 25},
{x: 2, y: 38},
<...>
```
But the chart also displays point x: 1.5 and others.
This happens, the value of x points can be reduced to a number.
How can I remove these intermediate points?

**Comment by kevinwarne** [comment]
You can accomplish this by specifying custom [d3.axis tickValues](https://github.com/d3/d3-axis#axis_tickValues) Here is a fiddle example: https://jsfiddle.net/mabt8dv5/2/

**Comment by kevinwarne** [comment]
Another option if you just want to specify how many ticks you want on the axis https://jsfiddle.net/mabt8dv5/3/
