### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jondavidjohn** [d2bjs/vue-d2b#4]
I noticed that the primary d2b project is licensed under the BSD 3-clause, but noticed this repo has no licensing information.  Is it safe to assume that you mean to have this vue wrapper licensed in the same manor? Is that something that could be added to this package?

**Comment by kevinwarne** [comment]
Good call, added it here: [3476b94](https://github.com/d2bjs/vue-d2b/commit/3476b947b8bf8424d69d0ece558c547677edab51)

Thanks!
