### ISSUE TITLE
Sankey tooltip error

### ISSUE THREAD

**Issue by doijunior** [d2bjs/vue-d2b#7]
I've copied the component from http://docs.d2bjs.org/vue-d2b/#/sankey but I'm having an erro:

`TypeError: tooltipUpdate.transition is not a function[Learn More]`

I'm using `"vue-d2b": "^2.0.0-beta.3",`

**Comment by kevinwarne** [comment]
Oops, I published that version without explicitly tagging it as a beta version. I'll try to get npm to add the beta tag so that it is not longer marked as @latest. In the mean time, install vue-d2b@1.0.15 and that should work better until 2.0 is ready.

**Comment by kevinwarne** [comment]
Okay this has been resolved. 1.0.15 is now back as the latest vue-d2b version. Thanks for letting me know!
